name: Checkstyle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Checkstyle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Luolastogeneraattori

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Checkstyle with Gradle
      run: ./gradlew checkstyleMain
